language: ruby
rvm:
- 2.5.1
before_script:
- gem install rest-client
script: ruby Tests.rb
after_success:
- ruby UpdateGem.rb
notifications:
  slack:
    secure: MGoacaKNK8IXylS1q+NKKxEFEcR37vzQEfwU8JxXTUuuOYzRQiY9RahG/wS0vklJA4BWW+tyz/lc/fn8Uc/pUvVc8vsUOjl8R2jSHkVJRXZPyGeinUfbOypyxPwEpV/kQVQUJMu4lFb3oB7U5IotLt+4aVqDz3GTKfDVR/dyoBQKl+0Qu3zJVzoiPeVH230+4rjYvSz0IyKVhVhtJvtTCQg/s5aNZs9JRkuHncuQaCC0hbt7tTMplGxkyCAzmAutXFcvYa0ojyF42AqcOhC3GZUsU1rXpGW0VIidTibltIc6Io9+3QRA/LN+sHD58P/RhmGIW1B/uYB+eRXpsD2SDYWSruB75I9v1VlAGX1CciQ/ID6Ng2obVX/70DmPnpuTkmO5Ew3hkY2NSkXBSJguYOF50SbCGXNoL1tACRgSLTY8HWn1jXlBoE0PogxgxVfNUo33TRr3AuSL+zNRslMtO5XGdnPUWKqBonYjncgVpFe6uMqWs9pEJBend0ih1Yn044z6PeZtv92tmSklQAwj5lIav10NcLZ45axTNIg0xLycXP+B6YlOENbkl01az2zSkAibskhbKvCQAmyFrxhuACyE7eX3i3Y0RxGbtzvZpdeHuzQnX35mkxlsRyQ+yw0fzSh2DAmVebD0pSEnR9llRKkpl4vHkioDShuaqg5PGC0=
    on_success: always
    on_failure: always
  email:
    on_success: never
    on_failure: never
